<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0;netstandard2.1</TargetFrameworks>

		<AssemblyName>YuJanggi.Protocol.V2</AssemblyName>
		<RootNamespace>YuJanggi.Protocol.V2</RootNamespace>
		
		<PackageId>YuJanggi.Protocol.V2</PackageId>
		<Version>0.2.0</Version>
		
		<LangVersion>9.0</LangVersion>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
		<PackageReference Include="System.Text.Json" Version="8.0.5" />
	</ItemGroup>

</Project>